### ISSUE TITLE
Error in install-upgrade-products when specific stemcell is required

### ISSUE THREAD

**Issue by gitmedur** [brightzheng100/platform-automation-pipelines#15]
Hi,
I need a specific stemcell version for PKS and Harbor so implemented the products.yaml as defined..
 pks:
    product-version: "1.6.0"
    pivnet-product-slug: pivotal-container-service
    pivnet-api-token: $token
    pivnet-file-glob: "*.pivotal"
    stemcell-iaas: vsphere
  pks-stemcell:                                   
    product-version: "123.45"                     
    pivnet-product-slug: stemcells-ubuntu-xenial
    pivnet-api-token: $token
    pivnet-file-glob: "bosh-stemcell-*-vsphere-esxi-ubuntu-xenial-go_agent.tgz"

  harbor:
    product-version: "1.9.3"
    pivnet-product-slug: harbor-container-registry
    pivnet-api-token: $token
    pivnet-file-glob: "*.pivotal"
    stemcell-iaas: vsphere
  harbor-stemcell:                                   
    product-version: "123.45"                     
    pivnet-product-slug: stemcells-ubuntu-xenial
    pivnet-api-token: $token
    pivnet-file-glob: "bosh-stemcell-*-vsphere-esxi-ubuntu-xenial-go_agent.tgz"

When running  ./3-fly-install-upgrade-products.sh -t ci -p prod-n install-upgrade-products -s true , i'm getting:

Error:
- assignment to entry in nil map (backtrace: goroutine 1 [running]:
    jobs-install-upgrade-with-specific-stemcell.lib.yml:96 in jobs
     L           #@yaml/text-templated-strings
    install-upgrade-products-with-specific-stemcell.yml:22 in <toplevel>
     L jobs: #@ jobs()

    reason:
     runtime/debug.Stack(0x8defc0, 0x8d9220, 0xa83d10)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
     github.com/k14s/ytt/pkg/template/core.ErrWrapper.func1.1(0xc0001fc3c0)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/template/core/errs.go:18 +0x9d
     panic(0x8d9220, 0xa83d10)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
     github.com/k14s/ytt/pkg/template.(*EvaluationCtx).TplStartNodeAnnotation(0xc0001070a0, 0xc00017c1b0, 0xc00015c750, 0xc000070ea0, 0x3, 0x3, 0x0, 0x0, 0x0, 0x8, ...)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/template/evaluation_ctx.go:135 +0x3d8
     github.com/k14s/ytt/pkg/template.(*CompiledTemplate).tplStartNodeAnnotation(...)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/template/compiled_template.go:227
     github.com/k14s/ytt/pkg/template/core.ErrWrapper.func1(0xc00017c1b0, 0xc00015c750, 0xc000070ea0, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/template/core/errs.go:25 +0xe9
     github.com/k14s/ytt/vendor/go.starlark.net/starlark.(*Builtin).CallInternal(0xc00015c750, 0xc00017c1b0, 0xc000070ea0, 0x3, 0x3, 0x0, 0x0, 0x0, 0xc000070ea0, 0xc0003c37e0, ...)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/go.starlark.net/starlark/value.go:622 +0x8b
     github.com/k14s/ytt/vendor/go.starlark.net/starlark.Call(0xc00017c1b0, 0xa98e40, 0xc00015c750, 0xc000070ea0, 0x3, 0x3, 0x0, 0x0, 0x0, 0xa99780, ...)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/go.starlark.net/starlark/eval.go:968 +0x154
     github.com/k14s/ytt/vendor/go.starlark.net/starlark.call(0xc00017c1b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0xc0001fcaf0, ...)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/go.starlark.net/starlark/interp.go:292 +0x405a
     github.com/k14s/ytt/vendor/go.starlark.net/starlark.(*Function).CallInternal(0xc00018a770, 0xc00017c1b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa99700, 0xdcdca0, ...)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/go.starlark.net/starlark/interp.go:39 +0x1c1
     github.com/k14s/ytt/vendor/go.starlark.net/starlark.Call(0xc00017c1b0, 0xa98ec0, 0xc00018a770, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa99700, ...)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/go.starlark.net/starlark/eval.go:968 +0x154
     github.com/k14s/ytt/vendor/go.starlark.net/starlark.call(0xc00017c1b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x70, 0xc000107110, 0xc00014d210, ...)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/go.starlark.net/starlark/interp.go:292 +0x405a
     github.com/k14s/ytt/vendor/go.starlark.net/starlark.(*Function).CallInternal(0xc000107110, 0xc00017c1b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7e03e9, 0x92bee0, ...)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/go.starlark.net/starlark/interp.go:39 +0x1c1
     github.com/k14s/ytt/vendor/go.starlark.net/starlark.Call(0xc00017c1b0, 0xa98ec0, 0xc000107110, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/go.starlark.net/starlark/eval.go:968 +0x154
     github.com/k14s/ytt/vendor/go.starlark.net/starlark.(*Program).Init(0xc00000e888, 0xc00017c1b0, 0xc00017c210, 0x0, 0x0, 0xc0000670e0)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/go.starlark.net/starlark/eval.go:340 +0x9a
     github.com/k14s/ytt/pkg/template.(*CompiledTemplate).eval(0xc000066ea0, 0xc00017c1b0, 0xc00017c210, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/template/compiled_template.go:140 +0x203
     github.com/k14s/ytt/pkg/template.(*CompiledTemplate).Eval(0xc000066ea0, 0xc00017c1b0, 0xa977c0, 0xc0000e7830, 0xc00017c1b0, 0xc00017c180, 0xc000106b60, 0x0, 0x0)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/template/compiled_template.go:101 +0x719
     github.com/k14s/ytt/pkg/workspace.(*TemplateLoader).EvalYAML(0xc0000e7830, 0xc00009a5f0, 0xc00009a370, 0x0, 0xc000160840, 0x8, 0x8)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/workspace/template_loader.go:172 +0x8be
     github.com/k14s/ytt/pkg/workspace.(*LibraryLoader).eval(0xc0001fdad8, 0x8c9820, 0xc0000e7800, 0x0, 0xc00014f2c0, 0xc00014fcc0, 0x0, 0x0, 0x0)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/workspace/library_loader.go:126 +0x6c4
     github.com/k14s/ytt/pkg/workspace.(*LibraryLoader).Eval(0xc0001fdad8, 0x8c9820, 0xc0000e7800, 0x8c9820, 0xc0000e7800, 0x0)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/workspace/library_loader.go:82 +0x5d
     github.com/k14s/ytt/pkg/cmd/template.(*TemplateOptions).RunWithFiles(0xc000078ea0, 0xc000062a40, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/cmd/template/cmd.go:118 +0x20d
     github.com/k14s/ytt/pkg/cmd/template.(*TemplateOptions).Run(0xc000078ea0, 0x0, 0x0)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/cmd/template/cmd.go:83 +0x255
     github.com/k14s/ytt/pkg/cmd/template.NewCmd.func1(0xc00009d680, 0xc00008e900, 0x0, 0x10, 0xf, 0xf)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/cmd/template/cmd.go:53 +0x2a
     github.com/k14s/ytt/pkg/cmd.reconfigureLeafCmd.func1(0xc00009d680, 0xc00008e900, 0x0, 0x10, 0x0, 0x0)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/cmd/ytt.go:89 +0x1b7
     github.com/k14s/ytt/vendor/github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc00009d680, 0xc00008e900, 0x0, 0x10, 0x0, 0x0)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/github.com/cppforlife/cobrautil/misc.go:25 +0xaf
     github.com/k14s/ytt/vendor/github.com/spf13/cobra.(*Command).execute(0xc00009d680, 0xc00008e600, 0x10, 0x10, 0xc00009d680, 0xc00008e600)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/github.com/spf13/cobra/command.go:762 +0x465
     github.com/k14s/ytt/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00009d180, 0xc00009d180, 0xe027e0, 0xc000053f58)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
     github.com/k14s/ytt/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/github.com/spf13/cobra/command.go:800
     main.main()
        /Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/cmd/ytt/ytt.go:17 +0x10b
     )
no changes to apply

Will you please redirect me for solving this issue?
Thanks,

**Comment by dashaun** [comment]
@gitmedur It looks like you have selected stemcell versions that don't exist.

for pks-stemcell try:

```
product-version: "456.51"
```

for harbor-stemcell try:

```
product-version: "456.100"
```

I grabbed those values from the release details on PivNet.

**Comment by gitmedur** [comment]
@dashaun Hi,
Seems i get the same error after changing to those stemcell versions. Actually i'm using stemcell version 456.77. Just changed it to 123.45 when pasting to web..

**Comment by dashaun** [comment]
Also change the file-glob lines:

For PKS and Harbor (needs the asterisk)
```
    pivnet-file-glob: "*.pivotal"
```
For both stemcells (also needs the asterisk)
```
    pivnet-file-glob: "bosh-stemcell-*-vsphere-esxi-ubuntu-xenial-go_agent.tgz"
```

**Comment by gitmedur** [comment]
This is my products.yml on the git server:


---

products:

  ## ==== Ops Manager
  opsman:
    product-version: "2.7.8"
    pivnet-product-slug: ops-manager
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "*.ova"

  ## ==== Products


  pks:
    product-version: "1.6.0"
    pivnet-product-slug: pivotal-container-service
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "*.pivotal"
    stemcell-iaas: vsphere

  pks-stemcell:                                   
    product-version: "456.77"                     
    pivnet-product-slug: stemcells-ubuntu-xenial
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "bosh-stemcell-*-vsphere-esxi-ubuntu-xenial-go_agent.tgz"
  

  harbor:
    product-version: "1.9.3"
    pivnet-product-slug: harbor-container-registry
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "*.pivotal"
    stemcell-iaas: vsphere

  harbor-stemcell:                                  
    product-version: "456.77"                     
    pivnet-product-slug: stemcells-ubuntu-xenial
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "bosh-stemcell-*-vsphere-esxi-ubuntu-xenial-go_agent.tgz"


Not sure, but it may be a problem with this line in templates/jobs-install-upgrade-with-specific-stemcell.lib.yml: 
 #@yaml/text-templated-strings
          - |
            stemcell_version="$( om interpolate \
            --config product-config-(@= product_alias @)-stemcell/semver-config-stemcell.yaml \
            --vars-file interpolated-files/((foundation))/config/global.yml \
            --path /product-version )"
            echo "{\"product\":\"(@= product_name @)\",\"stemcell\":\"$stemcell_version\"}" > assign-stemcell-config/config.yml

**Comment by gitmedur** [comment]
Ops Manager and Products have comment # at the beginning of the line..

**Comment by dashaun** [comment]
Can you point me to your git repo?  Is it public?

**Comment by gitmedur** [comment]
I wish i could, but it's private..
Please guide me for what you need..

**Comment by dashaun** [comment]
Here is a working example.  I think its just a formatting issue.

```
---

products:

  opsman:
    product-version: "2.8.3"
    pivnet-product-slug: ops-manager
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "ops-manager-vsphere-*.ova"

  pks:
    product-version: "1.6.1"
    pivnet-product-slug: pivotal-container-service
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "*.pivotal"
  pks-stemcell:
    product-version: "456.51"
    pivnet-product-slug: stemcells-ubuntu-xenial
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "bosh-stemcell-*-vsphere-esxi-ubuntu-xenial-go_agent.tgz"
```

**Comment by gitmedur** [comment]
As a slow learning person, i believe the response to "./3-fly-install-upgrade-products.sh -t ci -p dev -n install-upgrade-products -s true"  is so quick that it seems i'm even not going to git server.. Checked with a yaml linter, but no problem..

**Comment by brightzheng100** [comment]
@gitmedur I believe you have to re-format your yaml content -- it's space sensitive so please use 3 tillers (\`\`\`), which is called markdown annotation, to start and end with.

Please note that using the `-s true` flag is to have more flexibility to control the stemcell versions while upgrading/patching the platform and its components.

Please check out the sample repo, [here](https://github.com/brightzheng100/platform-automation-configuration), for the sample configs.

**Comment by gitmedur** [comment]
@brightzheng100 tried @dashaun 's working products.yml, but without success.


> 
> 
> Here is a working example. I think its just a formatting issue.
> 
> ```
> ---
> 
> products:
> 
>   opsman:
>     product-version: "2.8.3"
>     pivnet-product-slug: ops-manager
>     pivnet-api-token: ((pivnet_token))
>     pivnet-file-glob: "ops-manager-vsphere-*.ova"
> 
>   pks:
>     product-version: "1.6.1"
>     pivnet-product-slug: pivotal-container-service
>     pivnet-api-token: ((pivnet_token))
>     pivnet-file-glob: "*.pivotal"
>   pks-stemcell:
>     product-version: "456.51"
>     pivnet-product-slug: stemcells-ubuntu-xenial
>     pivnet-api-token: ((pivnet_token))
>     pivnet-file-glob: "bosh-stemcell-*-vsphere-esxi-ubuntu-xenial-go_agent.tgz"
> ```

**Comment by gitmedur** [comment]
Sorry to bother you.. Seems it's related to ytt version..I was using ytt version 0.15.0. Just updated to 0.26.0.
Thank you for your help.. Great work by the way.
